# -*- coding: utf-8 -*-
"""
印刷ワークの「B 一問一答」（用語入力）と「D 記述問題」（AI採点）を
公式LINEで出題するためのデータバンクを生成する。

- 一問一答: PDF生成と同じ pick_flashcards(14問) → 用語入力問題
    answer = ルビ記法の表記本体（例: 大宝律令）、reading = 読み（例: たいほうりつりょう）
- 記述: books/*.json の written（模範解答・指定語句つき）→ Gemini採点

出力: marutto-study/functions/src/generated/workbook-input-questions.generated.ts
（Firestoreには置かずビルド時生成のメモリバンク。回答記録は answers に残る）

実行: python -X utf8 export_workbook_input.py
"""
import json
import re
from pathlib import Path

import generate_history_workbook as g
from export_workbook_questions import GRADE_BY_CHAPTER

OUT_TS = Path(
    r"C:\Users\user\projects\education-apps\marutto-study\functions\src\generated\workbook-input-questions.generated.ts"
)

RUBY = re.compile(r"\{([^|{}]+)\|([^|{}]+)\}")


def ruby_base(s: str) -> str:
    return RUBY.sub(lambda m: m.group(1), s)


def ruby_reading(s: str) -> str:
    """ルビ部分は読みに、ルビのない部分はそのまま連結（例: {奈良|なら}時代 → なら時代）"""
    return RUBY.sub(lambda m: m.group(2), s)


BLANK = re.compile(r"\[\[([^\[\]]+)\]\]")

GRADE = GRADE_BY_CHAPTER


def main() -> None:
    index = {}
    n_terms = n_written = n_tl = 0
    for folder, spec in sorted(g.BOOKS.items()):
        # 理科など contentDir 持ちの章は LINE 連携未対応のためスキップ（後日対応）
        if spec.get("contentDir"):
            continue
        chapter = folder.split("-")[0]
        grade = GRADE[int(chapter)]
        era_dir = g.CONTENT_DIR / folder
        # 章内フラッシュカードから 表記→読み の逆引き（年表問題の読み許容用）
        reading_map = {}
        for tid in spec["topics"]:
            topic = json.loads((era_dir / f"{tid}.json").read_text(encoding="utf-8"))
            for c in topic["flashcards"]:
                reading_map.setdefault(ruby_base(c["front"]), ruby_reading(c["front"]))
            cards = g.pick_flashcards(topic["flashcards"], g.N_ITTOITTO)
            terms = []
            for n, c in enumerate(cards, 1):
                terms.append({
                    "id": f"q-wbt-history-{chapter}-{tid}-{n}",
                    "q": c["back"],
                    "a": ruby_base(c["front"]),
                    "reading": ruby_reading(c["front"]),
                    "expl": c.get("explanation", ""),
                })
            written = []
            for n, w in enumerate(spec.get("written", {}).get(tid, []), 1):
                written.append({
                    "id": f"q-wbw-history-{chapter}-{tid}-{n}",
                    "q": w["q"],
                    "keywords": w.get("keywords", []),
                    "model": w["a"],
                })
            index[topic["name"]] = {
                "subject": "history", "grade": grade,
                "terms": terms, "written": written,
            }
            n_terms += len(terms)
            n_written += len(written)

        # 年表でチェック → 用語入力問題（空欄1つにつき1問。他の空欄は答えを開示した文で出す）
        tl_terms = []
        qn = 0
        for year, ev in spec["timeline"]:
            blanks = BLANK.findall(ev)
            for bi, ans in enumerate(blanks):
                i = [0]
                def repl(m, bi=bi, i=i):
                    cur = i[0]
                    i[0] += 1
                    return "（　？　）" if cur == bi else m.group(1)
                qtext = BLANK.sub(repl, ev)
                qn += 1
                tl_terms.append({
                    "id": f"q-wbl-history-{chapter}-timeline-{qn}",
                    "q": f"【{year}】{qtext}　（？）に入る語句は？",
                    "a": ans,
                    "reading": reading_map.get(ans, ans),
                    "expl": f"{year}のできごと。ワークの「年表でチェック」で確認しよう。",
                })
        index[f"{spec['title']}の年表"] = {
            "subject": "history", "grade": grade,
            "terms": tl_terms, "written": [],
        }
        n_tl += len(tl_terms)

    lines = [
        "// AUTO-GENERATED by pdf-workbook/export_workbook_input.py — DO NOT EDIT.",
        "// 印刷ワークの「B 一問一答」（用語入力）と「D 記述問題」（AI採点）のメモリバンク。",
        "// 紙面と同一の問題。変更したら export を再実行して functions をデプロイする。",
        "",
        "export interface WorkbookTermQuestion {",
        "  id: string;",
        "  q: string;",
        "  /** 正答の表記（例: 大宝律令） */",
        "  a: string;",
        "  /** 正答の読み（例: たいほうりつりょう） */",
        "  reading: string;",
        "  expl: string;",
        "}",
        "",
        "export interface WorkbookWrittenQuestion {",
        "  id: string;",
        "  q: string;",
        "  keywords: readonly string[];",
        "  /** 模範解答 */",
        "  model: string;",
        "}",
        "",
        "export interface WorkbookInputTopic {",
        "  subject: string;",
        "  grade: string;",
        "  terms: readonly WorkbookTermQuestion[];",
        "  written: readonly WorkbookWrittenQuestion[];",
        "}",
        "",
        "export const WORKBOOK_INPUT_INDEX: Record<string, WorkbookInputTopic> = "
        + json.dumps(index, ensure_ascii=False, indent=1)
        + ";",
        "",
    ]
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print(f"terms: {n_terms}問 / written: {n_written}問 / 年表: {n_tl}問 / {len(index)}単元 → {OUT_TS}")


if __name__ == "__main__":
    main()
