# -*- coding: utf-8 -*-
"""
印刷ワークの「C 実戦問題」をそのまま公式LINEで出題するためのエクスポート。

PDF生成（generate_history_workbook.py）と同じ選定ロジック・同じシード付き
シャッフルを使うので、紙面に印刷された問題・選択肢の並び・正解位置と
完全に一致するデータが出力される。

出力:
 1. output/workbook-questions.json
      → marutto-study/scripts/sync-workbook-questions.ts が Firestore `questions` に同期
 2. marutto-study/functions/src/generated/workbook-question-index.generated.ts
      → webhook がメモリで単元→問題ID列を解決する index

実行: python -X utf8 export_workbook_questions.py
"""
import json
from pathlib import Path

import generate_history_workbook as g

FUNCTIONS_GENERATED = Path(
    r"C:\Users\user\projects\education-apps\marutto-study\functions\src\generated\workbook-question-index.generated.ts"
)
OUT_JSON = Path(__file__).parent / "output" / "workbook-questions.json"

# 章フォルダ → 学年（CLAUDE.md の学年フォルダ対応と同じ）
GRADE_BY_CHAPTER = {}
for i in range(1, 7):
    GRADE_BY_CHAPTER[i] = "中1"
for i in range(7, 13):
    GRADE_BY_CHAPTER[i] = "中2"
for i in range(13, 20):
    GRADE_BY_CHAPTER[i] = "中3"


def main() -> None:
    questions = []
    index = {}  # topic.name → {subject, grade, ids: []}

    for folder, spec in sorted(g.BOOKS.items()):
        # 理科など contentDir 持ちの章は LINE 連携未対応のためスキップ（後日対応）
        if spec.get("contentDir"):
            continue
        chapter_no = int(folder.split("-")[0])
        grade = GRADE_BY_CHAPTER[chapter_no]
        era_dir = g.CONTENT_DIR / folder
        for tid in spec["topics"]:
            topic = json.loads((era_dir / f"{tid}.json").read_text(encoding="utf-8"))
            # PDF と同一: pick_quiz → rebalance_quiz(seed=tid)
            quiz = g.rebalance_quiz(g.pick_quiz(topic["quiz"]["questions"], g.N_QUIZ), tid)
            ids = []
            chapter = folder.split("-")[0]  # 例 "09"。topicId が章をまたいで重複しても ID が衝突しないように含める
            for n, q in enumerate(quiz, 1):
                doc_id = f"q-wb-history-{chapter}-{tid}-{n}"
                ids.append(doc_id)
                questions.append({
                    "id": doc_id,
                    "subject": "history",
                    "grade": grade,
                    "topic": topic["name"],
                    "text": q["question"],
                    "choices": q["options"],
                    "correctChoiceId": q["correctIndex"],
                    "explanation": q.get("explanation", ""),
                    "difficulty": q.get("difficulty", "standard"),
                    "workbookOrder": n,
                    "contentTopicId": tid,
                    "bookFolder": folder,
                })
            index[topic["name"]] = {"subject": "history", "grade": grade, "ids": ids}

    OUT_JSON.parent.mkdir(exist_ok=True)
    OUT_JSON.write_text(
        json.dumps(questions, ensure_ascii=False, indent=1), encoding="utf-8"
    )
    print(f"JSON: {OUT_JSON} ({len(questions)}問 / {len(index)}単元)")

    lines = [
        "// AUTO-GENERATED by pdf-workbook/export_workbook_questions.py — DO NOT EDIT.",
        "// 印刷ワークの「C 実戦問題」の単元→問題IDインデックス。紙面と同一の問題・並び。",
        "// ワークの問題/選択肢を変えたら export を再実行し、sync-workbook-questions.ts で",
        "// Firestore を同期してから functions をデプロイすること。",
        "",
        "export interface WorkbookTopicMeta {",
        "  subject: string;",
        "  grade: string;",
        "  /** 紙面の (1)〜(8) と同じ順の問題ドキュメントID */",
        "  ids: readonly string[];",
        "}",
        "",
        "export const WORKBOOK_QUESTION_INDEX: Record<string, WorkbookTopicMeta> = "
        + json.dumps(index, ensure_ascii=False, indent=2)
        + ";",
        "",
    ]
    FUNCTIONS_GENERATED.write_text("\n".join(lines), encoding="utf-8")
    print(f"TS index: {FUNCTIONS_GENERATED}")


if __name__ == "__main__":
    main()
