# -*- coding: utf-8 -*-
"""
参考書 reference/*.json を、公式LINEの functions が使う TS インデックスに書き出す。

QRの t={章番号}-{topicId}（例 04-shotoku-asuka）をキーに、AI（Gemini）が
その単元の教材本文・用語・まとめを「接地情報」として引けるようにする。

出力: ../marutto-study/functions/src/generated/reference-topics.generated.ts
使い方: python -X utf8 export_reference_topics.py
※ 生成後、functions を build & デプロイすると LINE 側に反映される。
"""
import json
from pathlib import Path

BASE = Path(__file__).parent
REF = BASE / "reference"
OUT = (BASE.parent / "marutto-study" / "functions" / "src"
       / "generated" / "reference-topics.generated.ts")

GRADE = {**{f"{i:02d}": "中1" for i in range(1, 7)},
         **{f"{i:02d}": "中2" for i in range(7, 13)},
         **{f"{i:02d}": "中3" for i in range(13, 20)}}


def main() -> None:
    topics = {}
    for bp in sorted(REF.glob("*.json")):
        ch = bp.stem[:2]
        d = json.loads(bp.read_text(encoding="utf-8"))
        for t in d["topics"]:
            key = f"{ch}-{t['topicId']}"
            body = "\n".join(s.get("body", "") for s in t.get("sections", []))
            topics[key] = {
                "subject": "歴史",
                "grade": GRADE.get(ch, ""),
                "volume": d.get("volume", ""),
                "title": d.get("title", ""),
                "name": t.get("name", ""),
                "summary": t.get("summary", ""),
                "learn": t.get("learn", []),
                "terms": [
                    {"term": x.get("term", ""), "reading": x.get("reading", ""),
                     "desc": x.get("desc", "")}
                    for x in t.get("terms", [])
                ],
                "body": body,
            }

    header = "// AUTO-GENERATED by pdf-workbook/export_reference_topics.py — DO NOT EDIT\n\n"
    iface = (
        "export interface ReferenceTopic {\n"
        "  subject: string;\n  grade: string;\n  volume: string;\n  title: string;\n"
        "  name: string;\n  summary: string;\n  learn: string[];\n"
        "  terms: { term: string; reading: string; desc: string }[];\n"
        "  body: string;\n}\n\n"
    )
    data = ("export const REFERENCE_TOPICS: Record<string, ReferenceTopic> = "
            + json.dumps(topics, ensure_ascii=False, indent=1) + ";\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + iface + data, encoding="utf-8")
    print(f"{len(topics)} トピック → {OUT}")


if __name__ == "__main__":
    main()
